### ISSUE TITLE
Weird wording change in the license

### ISSUE THREAD

**Issue by ibbem** [skrieter/spldev#2]
The commit with the message *Revised LiteralList and SolutionList* changed the wording of the GPL licence. This was probably unintentional and should be reverted.

All repositories, this one and all sub repositories referenced by `scripts/repo.txt`, are affected.

The offending commit has to following structure:
`git log -p -n 1 -- COPYING`
```diff
commit be271b75f2e285c68943883fbac44e1bb512fc02 (origin/main, origin/HEAD)
Author: Elias Kuiter <info@elias-kuiter.de>
Date:   Tue Nov 8 22:05:08 2022 +0100

    Revised LiteralList and SolutionList

diff --git a/COPYING b/COPYING
index f288702..47742fc 100644
--- a/COPYING
+++ b/COPYING
@@ -615,7 +615,7 @@ SUCH DAMAGES.
 above cannot be given local legal effect according to their terms,
 reviewing courts shall apply local law that most closely approximates
 an absolute waiver of all civil liability in connection with the
-Program, unless a warranty or assumption of liability accompanies a
+Program, unless a warranty or assumable of liability accompanies a
 copy of the Program in return for a fee.
 
                      END OF TERMS AND CONDITIONS
```

For reference, the commit id of each sub repository is as follows:

| Repository directory name       | Commit hash                                |
|---------------------------------|--------------------------------------------|
| .                               | `be271b75f2e285c68943883fbac44e1bb512fc02` |
| base                            | `13da1f2040174fff6ff7090d2c39aa71c9e152dd` |
| bin-javasmt                     | `7981019c5dd4bc378f3ee204243509fc925c1ff1` |
| bin-sharpsat                    | `6017737db67af191f0ed77f58430f11fa71c77c0` |
| cli                             | `912a0f99b3bb14131e4474b3e785ec52ae7c3561` |
| feature-model                   | `1a22a541cfc7638808d7547a7c4ce466a6e0e83a` |
| feature-modeling                | `1a22a541cfc7638808d7547a7c4ce466a6e0e83a` |
| formula-analysis-javasmt        | `aa755699d386c9d26024bcac1b477126418eb9a3` |
| formula-analysis-sat4j          | `574fb7da6494dd948ac3015a21d66719edf92940` |
| formula-analysis-sat4j-sharpsat | `bc4518075d2ef0f5f8a3c64aa8b24a90d5c54a53` |
| formula-analysis-sharpsat       | `a0aad6cce95f7338d72a5c9d7466138d3f70dd9e` |
| formula                         | `bae2a7b13586e4ca10c15054a859a4eb915b43cb` |
| gradle-plugins                  | `f9f3bf29aa93475175d791bb275ef336633f7564` |
| util-evaluation                 | `4bc9302f55c8f5d377fa7b7842db177b67ce227d` |

**Comment by ekuiter** [comment]
you are right, thanks :) an IntelliJ refactoring fail

**Comment by ekuiter** [comment]
fixed now both on stable and main
