### ISSUE TITLE
Outdated repository in repo.txt

### ISSUE THREAD

**Issue by h3ssto** [skrieter/spldev#6]
It appears that https://github.com/FeatureIDE/FeatJAR-bin-kissat/ is either invalid or private.

Therefore, `git` asks for username + password during its futile task of accessing the repo. Anyways, this breaks the depicted installation procedure.

Fix: Remove the repo from `repo.txt`.

**Comment by skrieter** [comment]
Fixed.
We merged all bin projects with the respective analysis projects.
